spring:
  application:
    name: APP_MATRICULA
  datasource:
    url: ${BD_URL}
    username: ${BD_USER}
    password: ${BD_PASS}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 1800000
  threads:
    virtual:
      enabled: true

