spring:
  application:
    name: APP_MATRICULA
  cache:
    type: redis
    redis:
      time-to-live: 600000
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASS}
  datasource:
    url: ${BD_URL}
    username: ${BD_USER}
    password: ${BD_PASS}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 1800000
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  threads:
    virtual:
      enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/spring-boot-realm-dev
          jwk-set-uri: http://localhost:9090/realms/spring-boot-realm-dev/protocol/openid-connect/certs
logging:
  level:
    org:
      keycloak: DEBUG
      springframework:
        security: TRACE

jwt:
  auth:
    converter:
      principle-attribute: preferred_username
      resource-id: ${RESOURCE_ID}
  role-user: ${ROLE_USER}





